menu:
- {name: 'home', url: '/index'}
- {name: 'more about me', url: '/post'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Maybe add courses here?'}
more about me:
- {name: Blog}

social:
- {icon: 'github', link: 'https://github.com/astrogirl1'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/meera-deshpande'}

contacts:
- {name: 'Meera Deshpande', title: 'Astrophysicist', department: 'Physics & Astronomy', institution: 'University of Adelaide', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
